import {sharedRoutines, mutationQueue, routineTime} from './shared-routines.mjs';
import {KIDS,TASKS,CATEGORIES,ITEMS,ACHIEVEMENTS,normalize,dayKey,streak,complete,buy,resetRoutine,ledger} from './game.mjs';
import {readLocal,connect} from './store.mjs';
import {connectDemo} from './demo-store.mjs';
const isDemo=new URLSearchParams(location.search).get('demo')==='1';
import {world,escapeHTML as esc} from './world.mjs';
let data=normalize(isDemo?{}:readLocal()),selected=null,page='home',category='stadion',store=null,status='connecting';
const $=s=>document.querySelector(s),kid=()=>data.kids[selected];
const time=s=>s===null?'Ingen tid målt':Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');
const action=(a,label,cls='',extra='')=>`<button class="${cls}" data-action="${a}" ${extra}>${label}</button>`;
function notify(message){$('#notice').textContent=message;$('#notice').classList.add('visible');clearTimeout(notify.t);notify.t=setTimeout(()=>$('#notice').classList.remove('visible'),4500);}
function popup(html,celebrate=false){$('#dialogBody').innerHTML=html;$('#dialog').showModal();if(celebrate && !matchMedia('(prefers-reduced-motion: reduce)').matches)for(let i=0;i<24;i++){const el=document.createElement('span');el.className='confetti';el.textContent=['⭐','✨','⚽'][i%3];el.style.left=Math.random()*100+'vw';el.style.animationDuration=(1.8+Math.random()*1.5)+'s';document.body.append(el);setTimeout(()=>el.remove(),3500);}}
$('#closeDialog').onclick=()=>$('#dialog').close();
function sync(s){status=s;$('#sync').textContent=({demo:'DEMO · kun på denne enhed',connecting:'Forbinder…',ready:'● Gemt i fællesskab',offline:'Offline · viser senest gemt',error:'Forbindelsen mangler', 'backup-error':'Gemt i skyen · lokal backup fuld'})[s];}
const enqueueMutation = mutationQueue();
async function mutate(fn) {
  return enqueueMutation(async () => {
    if (!store || !['ready','backup-error','demo'].includes(status) || (!isDemo && !navigator.onLine)) {
      notify('Forbind til internettet, så dine stjerner kan gemmes sikkert.');
      return;
    }
    try { return await store.mutate(fn); }
    catch (e) { notify(e.message || 'Kunne ikke gemme. Prøv igen.'); }
  });
}
$('#unlock').onsubmit=async e=>{e.preventDefault();if(!isDemo && $('#pinInput').value!=='0605'){$('#pinError').textContent='Forkert kode';$('#pinInput').value='';return;}$('#lockScreen').hidden=true;$('#mainApp').hidden=false;render();try{store=await (isDemo?connectDemo:connect)(d=>{data=d;render();},sync);}catch{sync('error');notify('Kunne ikke forbinde til den fælles konto. Genindlæs for at prøve igen.');}};
if(isDemo){$('#unlock h1').textContent='Prøv din egen fodboldklub';$('#unlock>p:not(.eyebrow)').textContent='Demo med separate testdata. Familiens konto bliver ikke ændret.';$('#pinInput').required=false;$('#pinInput').hidden=true;$('#unlock label').hidden=true;$('#unlock button').textContent='Start demo →';}
function badge(k){return `<span class="club-badge" style="--club:${esc(k.club.primary)};--second:${esc(k.club.secondary)}">${esc(k.club.logo)}</span>`;}
function header(){const k=kid();return `<div class="kidbar">${action('home','← Alle børn','back')}<span>${esc(selected)}s klub</span><strong>⭐ ${k.stars}</strong></div>`;}
function dashboard(){const k=kid(),goal=ITEMS.find(i=>i.id===k.goal);return `${header()}<section class="club-heading"><div>${badge(k)}<p class="eyebrow">FRA GRÆSPLÆNE TIL DRØMMEKLUB</p><h1>${esc(k.club.name)}</h1><p>En god dag begynder med en lille sejr.</p></div><div class="streak">🔥 <strong>${streak(k)}</strong><span>dage i træk</span></div></section><div class="dashboard-grid"><section class="world-card"><div class="world-label"><span>⚽ DIT KLUBOMRÅDE</span><span>${Object.keys(k.purchases).length} / ${ITEMS.length} bygget</span></div>${world(k)}<div class="world-footer"><span>${goal?`Næste drøm: <strong>${esc(goal.name)}</strong> · ${Math.max(0,goal.price-k.stars)} ⭐ tilbage`:'Din klub venter på din næste idé.'}</span>${action('club','Besøg min klub ↗','primary')}</div></section><aside class="daily"><p class="eyebrow">DINE DAGLIGE SEJRE</p><h2>Klar, parat …</h2>${['morgen','aften'].map(t=>`<button class="routine-card ${t}" data-action="routine" data-type="${t}"><span class="routine-icon">${t==='morgen'?'☀️':'🌙'}</span><span><strong>${t==='morgen'?'Morgen':'Aften'}</strong><small>${k.history[data.date]?.[t]?'✓ Gennemført i dag':TASKS[t].length+' opgaver · op til 10 ⭐'}</small></span><span>→</span></button>`).join('')}<div class="tip"><span>💡</span><p>Byg lidt i dag.<br>Eller spar op til noget stort.<br><strong>Du bestemmer.</strong></p></div>${action('achievements','🏆 Se dine milepæle','text-button')}</aside></div>`;}
function identity(){const k=kid();popup(`<p class="eyebrow">DIN HELT EGEN KLUB</p><h2>${k.club.created?'Klubbens identitet':'Velkommen som klubejer!'}</h2><p>Du har fået en græsplæne, to gamle mål og én bold. Resten bygger du selv.</p><form id="identity"><label>Klubnavn<input name="name" maxlength="32" required value="${esc(k.club.name)}"></label><div class="form-row"><label>Primær farve<input name="primary" type="color" value="${esc(k.club.primary)}"></label><label>Sekundær farve<input name="secondary" type="color" value="${esc(k.club.secondary)}"></label></div><label>Klublogo<select name="logo">${['🛡️','⚽','🦁','🦅','🐉','⚡'].map(l=>`<option ${l===k.club.logo?'selected':''}>${l}</option>`).join('')}</select></label><button class="primary">Gem min klub</button></form>`);const name=selected;$('#identity').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),club=Object.fromEntries(f);club.name=club.name.trim();if(!club.name)return;const ok=await mutate(s=>{s.kids[name].club={...club,created:true};return true;});if(ok){$('#dialog').close();render();}};}
function club(){const k=kid();return `${header()}<div class="section-heading"><div><p class="eyebrow">DU ER KLUBEJEREN</p><h1>${esc(k.club.name)}</h1></div>${action('identity','✎ Klubnavn & farver','secondary')}</div><section class="world-card club-world">${world(k)}<div class="world-footer"><strong>${Object.keys(k.purchases).length} forbedringer bygget</strong><span>⭐ ${k.stars} at bygge for</span></div></section><div class="section-heading"><div><p class="eyebrow">HVAD DRØMMER DU OM?</p><h2>Byg din klub</h2></div><span class="muted">Vælg din egen vej</span></div><div class="tabs" role="group" aria-label="Byggekategorier">${Object.entries(CATEGORIES).map(([id,title])=>action('category',title,category===id?'active':'',`data-id="${id}" aria-pressed="${category===id}"`)).join('')}</div><div class="shop-grid">${ITEMS.filter(i=>i.category===category).map(i=>{const owned=k.purchases[i.id],locked=i.requires.some(id=>!k.purchases[id]);return `<article class="upgrade ${owned?'owned':''}"><div class="upgrade-top"><span class="item-icon">${owned?'✓':locked?'🔒':CATEGORIES[i.category].split(' ')[0]}</span><strong>${owned?'Bygget':i.price+' ⭐'}</strong></div><h3>${i.name}</h3><p>${i.visual}</p><small>${owned?'En del af din klub':locked?'Kræver: '+i.requires.map(id=>ITEMS.find(x=>x.id===id).name).join(', '):'Ca. '+Math.ceil(i.price/20)+' dag'+(i.price>20?'e':'')+' ved 20 ⭐/dag'}</small><div class="purchase-actions">${action('buy',owned?'✓ Ejet':locked?'🔒 Se krav':k.stars<i.price?'Mangler '+(i.price-k.stars)+' ⭐':'Køb · '+i.price+' ⭐',owned?'secondary':'primary',`data-id="${i.id}" ${owned?'disabled':''}`)}${owned?'':action('goal',k.goal===i.id?'♥ Dit mål':'♡ Spar op','goal-button',`data-id="${i.id}"`)}</div></article>`;}).join('')}</div>`;}
function achievements(){const k=kid();return `${header()}<p class="eyebrow">HVERDAGENS MESTER</p><h1>Små sejre bliver store</h1><p>Begge rutiner på én dag tæller som en streak-dag. Særlige præmier bliver dine for altid.</p><div class="stats"><div>🔥 <strong>${streak(k)}</strong><span>dage i træk nu</span></div><div>🏆 <strong>${k.bestStreak}</strong><span>bedste streak</span></div><div>✓ <strong>${Object.values(k.history).reduce((n,d)=>n+Object.keys(d).length,0)}</strong><span>rutiner gennemført</span></div></div><div class="achievement-grid">${ACHIEVEMENTS.map(a=>`<article class="achievement ${k.achievements[a.days]?'earned':''}"><span>${a.icon}</span><h3>${a.name}</h3><p>${a.days} dage i træk${a.stars?' · +'+a.stars+' ⭐':''}</p><small>${k.achievements[a.days]?'✓ Vundet '+k.achievements[a.days]:'🔒 '+Math.max(0,a.days-streak(k))+' dage til næste milepæl'}</small></article>`).join('')}</div>`;}
function stars(){const k=kid();return `${header()}<p class="eyebrow">KLUBKONTOEN</p><h1>⭐ ${k.stars} stjerner</h1><p>Din opsparing til næste store klubdrøm.</p><div class="reward-info"><h2>Sådan tjener du stjerner</h2><p>Gennemfør en hel rutine: <strong>5 ⭐</strong></p><p>Under 10 min: +2 · Under 7 min: +2 mere · Under 5 min: +1 mere</p><p>Op til 20 ⭐ om dagen fra rutiner. Sponsorbonus kommer oveni én gang.</p></div><h2>Seneste bevægelser</h2><div class="ledger">${k.ledger.length?k.ledger.slice(-50).reverse().map(l=>`<div><span><strong>${esc(l.label)}</strong><small>${esc(l.date)}</small></span><b class="${l.amount>0?'positive':''}">${l.amount>0?'+':''}${l.amount} ⭐</b></div>`).join(''):'<p>Dine tidligere stjerner er bevaret. Nye belønninger og køb vises her.</p>'}</div>`;}
function render(){if($('#mainApp').hidden)return;if(['morgen','aften'].includes(page)){$('#view').innerHTML=sharedRoutines(data,page);$('#nav').innerHTML='';return;}if(!selected){$('#view').innerHTML=`<section class="welcome"><p class="eyebrow">VELKOMMEN TIL VANGKILDE TODO</p><h1>Hvem er klar til<br>at bygge noget stort?</h1><p>Gør dine opgaver. Tjen stjerner. Byg din egen fodboldklub.</p></section><section class="family-routines" aria-label="Fælles rutiner"><div><p class="eyebrow">KLAR SAMMEN PÅ ÉN SKÆRM</p><h2>Jeres fælles ToDo</h2></div><div class="family-routine-buttons">${action('routine','☀️ Morgen · alle tre','primary','data-type="morgen"')}${action('routine','🌙 Aften · alle tre','secondary','data-type="aften"')}</div></section><div class="children">${KIDS.map((name,i)=>{const k=data.kids[name];return `<button class="child-card child-${i}" data-action="select" data-name="${name}">${badge(k)}<span class="eyebrow">KLUBEJER ${String(i+1).padStart(2,'0')}</span><h2>${name}</h2><p>${esc(k.club.name)}</p><div><strong>⭐ ${k.stars}</strong><span>🔥 ${streak(k)} dage</span></div><b class="enter-club">Ind i klubben →</b></button>`;}).join('')}</div><p class="home-note">En græsplæne i dag. Måske et helt stadion i morgen.</p>`;$('#nav').innerHTML='';return;}
 $('#view').innerHTML=page==='home'?dashboard():page==='club'?club():page==='stars'?stars():achievements();
 $('#nav').innerHTML=[['home','⌂','Overblik'],['morgen','☀️','Morgen'],['aften','🌙','Aften'],['club','⚽','Min klub'],['stars','⭐','Stjerner'],['achievements','🏆','Præmier']].map(([id,icon,label])=>action('page',`<span>${icon}</span><small>${label}</small>`,page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`)).join('');
}
async function parent(){popup(`<p class="eyebrow">FORÆLDREADGANG</p><h2>Klubbens kontor</h2><form id="parentPin"><label>Forældrekode<input name="pin" type="password" inputmode="numeric" maxlength="4" required></label><button class="primary">Åbn kontoret</button><p id="parentError" role="alert"></p></form>`);$('#parentPin').onsubmit=e=>{e.preventDefault();if(new FormData(e.target).get('pin')!=='0605'){$('#parentError').textContent='Forkert kode';return;}$('#dialogBody').innerHTML=`<h2>Klubbens kontor</h2><form id="admin"><label>Barn<select name="kid">${KIDS.map(n=>`<option ${n===selected?'selected':''}>${n}</option>`).join('')}</select></label><label>Justér stjerner (+ eller −)<input type="number" name="amount" step="1" value="0" min="-10000" max="10000" required></label><label>Begrundelse<input name="reason" maxlength="100" value="Forældrejustering" required></label><button class="primary">Gem justering</button><hr><label>Rutine<select name="routine"><option value="morgen">Morgen</option><option value="aften">Aften</option></select></label><button type="button" id="reset" class="secondary">Nulstil denne rutine</button><p class="muted">Nulstilling bevarer køb, stjerner og historik. Samme rutine giver aldrig belønning to gange på samme dag.</p></form>${action('export','↓ Hent sikkerhedskopi','secondary')}`;
 $('#admin').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('kid'),amount=Number(f.get('amount')),reason=f.get('reason');if(!Number.isInteger(amount)||Math.abs(amount)>10000)return;const ok=await mutate(s=>{const k=s.kids[name];if(k.stars+amount<0)throw Error('Beholdningen må ikke blive negativ.');k.stars+=amount;ledger(k,amount,reason,s.date);return true;});if(ok)notify('Justering gemt.');};
 $('#reset').onclick=async()=>{const f=new FormData($('#admin'));if(!confirm('Nulstil '+f.get('routine')+' for '+f.get('kid')+'?'))return;const ok=await mutate(s=>{resetRoutine(s,f.get('kid'),f.get('routine'));return true;});if(ok)notify('Rutinen er nulstillet.');};};}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b || b.disabled)return;const a=b.dataset.action;
 if(a==='home'){selected=null;page='home';render();}
 if(a==='select'){selected=b.dataset.name;page='home';render();}
 if(a==='page'||a==='routine'||a==='club'||a==='achievements'){page=b.dataset.page||b.dataset.type||a;render();window.scrollTo(0,0);if(page==='club'&&!kid().club.created)identity();}
 if(a==='child-club'){selected=b.dataset.name;page='club';render();window.scrollTo(0,0);if(!kid().club.created)identity();}
 if(a==='identity')identity();
 if(a==='category'){category=b.dataset.id;render();}
 if(a==='start'){const n=b.dataset.name,t=b.dataset.type;if(!KIDS.includes(n)||!TASKS[t])return;await mutate(s=>{const r=s.kids[n].routines[t];if(!r.start&&!r.finished)r.start=Date.now();});}
 if(a==='task') {
   const n=b.dataset.name,t=b.dataset.type,i=Number(b.dataset.index);
   if(!KIDS.includes(n)||!TASKS[t]||!Number.isInteger(i)||!TASKS[t][i])return;
   // Capture the desired value at the tap, so a double tap on a pending
   // unchecked task cannot undo it when the queued transaction runs.
   const checked=b.getAttribute('aria-pressed')!=='true';
   await mutate(s=>{
     const k=s.kids[n],r=k.routines[t];
     if(r.finished)return null;
     if(r.start===null)r.start=Date.now();
     s.checks[t][n+'_'+i]=checked;
     return complete(s,n,t);
   });
   // Completion is rendered from committed history inside this child's
   // column; never open a modal or scatter confetti over the shared screen.
 }
 if(a==='goal'){const n=selected,id=b.dataset.id;await mutate(s=>{s.kids[n].goal=id;});notify('Din næste klubdrøm er valgt.');}
 if(a==='buy'){const n=selected,id=b.dataset.id,k=kid(),item=ITEMS.find(i=>i.id===id),missing=item.requires.filter(x=>!k.purchases[x]);if(missing.length){popup('<h2>🔒 Først skal du bygge…</h2><p>'+missing.map(x=>ITEMS.find(i=>i.id===x).name).join(' og ')+'</p>');return;}if(k.stars<item.price){popup(`<h2>En drøm at spare op til</h2><p>Du mangler ${item.price-k.stars} ⭐ til ${item.name}.</p>${action('goal','♡ Gør til mit mål','secondary',`data-id="${id}"`)}`);return;}const result=await mutate(s=>buy(s,n,id));if(result)popup(`<div class="celebrate-icon">🏗️</div><p class="eyebrow">NY OPGRADERING!</p><h2>${result.name}</h2><p>${esc(data.kids[n].club.name)} har fået ${result.name.toLocaleLowerCase('da')}!</p><p>Se, hvordan dit klubområde har ændret sig.</p>`,true);}
 if(a==='parent')parent();
 if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='VangkildeToDo-backup-'+dayKey()+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
setInterval(()=>{
  if(data.date!==dayKey()){data=normalize(data);render();}
  if(['morgen','aften'].includes(page))for(const el of document.querySelectorAll('[data-clock]')){
    const r=data.kids[el.dataset.clock].routines[page];
    if(r.start!==null&&!r.finished)el.textContent=routineTime(Math.max(0,(Date.now()-r.start)/1000));
  }
},500);
window.addEventListener('offline',()=>{if(!isDemo)sync('offline');});
